# Generated by Django 5.2.3 on 2025-06-15 23:35

from django.db import migrations

def assign_permissions(apps, _):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    content_type = ContentType.objects.get(app_label='team', model='teammember')

    admin_group, _ = Group.objects.get_or_create(name='admin')
    regular_group, _ = Group.objects.get_or_create(name='regular')

    add_perm = Permission.objects.get(content_type=content_type, codename='add_teammember')
    change_perm = Permission.objects.get(content_type=content_type, codename='change_teammember')
    delete_perm = Permission.objects.get(content_type=content_type, codename='delete_teammember')
    view_perm = Permission.objects.get(content_type=content_type, codename='view_teammember')

    admin_group.permissions.set([add_perm, change_perm, delete_perm, view_perm])
    regular_group.permissions.set([add_perm, view_perm, change_perm])

def remove_permissions(apps, _):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='admin').delete()
    Group.objects.filter(name='regular').delete()

class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(assign_permissions, remove_permissions),
    ]
