# Generated by Django 5.2.3 on 2025-06-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_assign_group_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
